### PR TITLE
Scroll camera when holding down

### PR DESCRIPTION
**Pull request by tilderain**
I've added a new button to the game. I call it the "SkyTheLeafeon Destroyer"

https://user-images.githubusercontent.com/7954485/195726028-f2eb6019-a94a-435b-96aa-b1b1e8820eaa.mp4

[doukutsu-en-downscroll.zip](https://github.com/andwn/cave-story-md/files/9781598/doukutsu-en-downscroll.zip)

### CODE REVIEW

**Comment by andwn** [comment]
Wait...was it supposed to do that the whole time?

**Comment by mastercheff** [comment]
Maybe in the GBA port it would come more useful, much like mario advance series of ports. I'm more interested in fixing nemesis and Santa's encounter than qol improvements :)

**Comment by tilderain** [comment]
> Wait...was it supposed to do that the whole time?

Absolutely

> I'm more interested in fixing nemesis and Santa's encounter than qol improvements :)

You can't win them all

**Comment by andwn** [comment]
Just tried in the PC game and yeah it was indeed supposed to be like that the whole time, whoops.

> I'm more interested in fixing nemesis and Santa's encounter than qol improvements :)

Sounds great, looking forward to your pull request (Santa was fixed last week though).

Actually the Nemesis issue is probably just that the vertical sprite tiles got put in the wrong place in VRAM.

**Pull request merged**
